force-app/main/default/objects/State_to_Zone_Mapping__mdt/State_to_Zone_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Maps Indian states to their corresponding zones.</description>
    <label>State to Zone Mapping</label>
    <pluralLabel>State to Zone Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/State_to_Zone_Mapping__mdt/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North India</fullName>
                <default>true</default>
                <label>North India</label>
            </value>
            <value>
                <fullName>South India</fullName>
            </value>
            <value>
                <fullName>East India</fullName>
            </value>
            <value>
                <fullName>West India</fullName>
            </value>
            <value>
                <fullName>Union Territory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClassesWith/AccountTriggerHandler.cls
/**
 * @description       : 
 * @author            : Kanishk Singhal
 * @group             : 
 * @last modified on  : 02-15-2025
 * @last modified by  : Kanishk Singhal
**/
public with sharing class AccountTriggerHandler {

    // Trigger handler methods for populate the Zone field
    public static void onBeforePopulateTheZone(List<Account> newAccounts) {
        set <String> states = new Set<String>();
        for (Account acc : newAccounts) {
            states.add(acc.BillingState);
        }

        Map<String, String> stateToZoneMap = new Map<String, String>();
        list<State_to_Zone_Mapping__mdt> stateAndZones = [SELECT State__c, Zone__c FROM State_to_Zone_Mapping__mdt WHERE MasterLabel IN :states];

        for(State_to_Zone_Mapping__mdt zoneMapToState : stateAndZones){
            stateToZoneMap.put(zoneMapToState.State__c, zoneMapToState.Zone__c);
        }
        for (Account acc : newAccounts) {
            if(stateToZoneMap.containsKey(acc.BillingState)){
                acc.Zone__c = stateToZoneMap.get(acc.BillingState);
            }else{
                continue;
            }
        }
    }
}