force-app/main/default/objects/Car_Model__c/Car_Model__c.object-meta.xml
<CustomObject>
    <label>Car Model</label>
    <nameField>
        <label>Car Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Model__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Car Models</relationshipLabel>
    <relationshipName>Car_Models</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ClassesWith/OpportunityTriggerHandler.cls
/**
 * @description       : 
 * @author            : Kanishk Singhal
 * @group             : 
 * @last modified on  : 02-15-2025
 * @last modified by  : Kanishk Singhal
**/
public with sharing class OpportunityTriggerHandler {
   public static void createCarModelRecordOnCloseWon(List<Opportunity> newOpportunities){
        List<Car_Model__c> carModelList = new List<Car_Model__c>();
        for(Opportunity opp : newOpportunities){
            if(opp.StageName == 'Closed Won'){
                Car_Model__c carModel = new Car_Model__c();
                // carModel.Name = opp.Name;
                // carModel.Model__c = opp.Model__c;
                carModel.Account__c = opp.AccountId;
                
                carModelList.add(carModel);
            }
        }
        insert carModelList;
   }
}